name: Node.js CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  cypress-chrome:
    name: test-cypress
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.6]

    steps:
      - uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/bun.lockb') }}
      - name: Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Start Server
        run: |
          timeout=0
          until [ $timeout -ge 60 ]
          do
            (bun server &) && break
            sleep 5
            timeout=$((timeout+5))
          done
      - name: Wait for server
        run: |
          timeout=0
          until [ $timeout -ge 60 ]
          do
            wget --spider http://localhost:3100 2>/dev/null
            if [ $? -eq 0 ]; then
              break
            fi
            sleep 5
            timeout=$((timeout+5))
          done
      - name: Cypress info
        run: bunx cypress info
      - name: Cypress run
        uses: cypress-io/github-action@v6.7.2
        with:
          browser: chrome
    