name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    - name: Cypress - Chrome
      uses: cypress-io/github-action@v4.2.0
      with:
          start: npm run server
          wait-on: 'http://localhost:3000'
          browser: chrome
    - name: Cypress - Firefox
      uses: cypress-io/github-action@v4.2.0
      with:
          start: npm run server
          browser: firefox
          fail-fast: false
    - name: Cypress - Safari
      uses: cypress-io/github-action@v4.2.0
      with:
          start: npm run server
          browser: webkit
