name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    - run: npm run lint-check

  cypress-chrome:
    name: cypress-chrome
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:    
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    - name: Cypress run
      uses: cypress-io/github-action@v4.2.0
      with:
        start: npm run server
        wait-on: 'http://localhost:3000'
        browser: chrome

  cypress-safari:
    name: cypress-safari
    needs: [build, cypress-chrome]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:    
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    - run: npx playwright install-deps webkit
    - name: Cypress run
      uses: cypress-io/github-action@v4.2.0
      with:
        start: npm run server
        wait-on: 'http://localhost:3000'
        browser: webkit