name: Cypress Tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  cypress-chrome:
    name: test-cypress
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Start Server
        run: |
          timeout=0
          until [ $timeout -ge 60 ]
          do
            (bun server &) && break
            sleep 5
            timeout=$((timeout+5))
          done
      - name: Wait for server
        run: |
          timeout=0
          until [ $timeout -ge 60 ]
          do
            wget --spider http://localhost:3100 2>/dev/null
            if [ $? -eq 0 ]; then
              break
            fi
            sleep 5
            timeout=$((timeout+5))
          done
      - name: Cypress info
        run: bunx cypress info
      - name: Cypress run
        run: bunx cypress run --browser chrome --headless
    