name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Install Dev Dependencies
        run: npm install
      - name: Lint Check
        run: npm run lint-check

  cypress-chrome:
    name: test-cypress
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: npm ci
      - name: Start Server
        run: |
          timeout=0
          until [ $timeout -ge 60 ]
          do
            (bun server &) && break
            sleep 5
            timeout=$((timeout+5))
          done
      - name: Wait for server
        run: |
          timeout=0
          until [ $timeout -ge 60 ]
          do
            wget --spider http://localhost:3100 2>/dev/null
            if [ $? -eq 0 ]; then
              break
            fi
            sleep 5
            timeout=$((timeout+5))
          done
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.0
        with:
          browser: chrome
